### ISSUE TITLE
mup deploy failed

### ISSUE THREAD

**Issue by xiya233** [guidouil/TorrentsDuck#7]
Started TaskList: Pushing Meteor App
[xxx] - Pushing Meteor App Bundle to the Server
[xxx] - Pushing Meteor App Bundle to the Server: SUCCESS
[xxx] - Prepare Bundle
[xxx] x Prepare Bundle: FAILED

	npm ERR! code ECONNRESET
	npm ERR! errno ECONNRESET
	npm ERR! network request to https://registry.npmjs.org/node-pre-gyp failed, reason: socket hang up
	npm ERR! network This is a problem related to network connectivity.
	npm ERR! network In most cases you are behind a proxy or have bad network settings.
	npm ERR! network 
	npm ERR! network If you are behind a proxy, please make sure that the
	npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

PING registry.npmjs.org (104.16.17.35) 56(84) bytes of data.
64 bytes from 104.16.17.35 (104.16.17.35): icmp_seq=1 ttl=61 time=1.06 ms
64 bytes from 104.16.17.35 (104.16.17.35): icmp_seq=2 ttl=61 time=0.848 ms
64 bytes from 104.16.17.35 (104.16.17.35): icmp_seq=3 ttl=61 time=1.02 ms
64 bytes from 104.16.17.35 (104.16.17.35): icmp_seq=4 ttl=61 time=0.825 ms
64 bytes from 104.16.17.35 (104.16.17.35): icmp_seq=5 ttl=61 time=1.03 ms
64 bytes from 104.16.17.35 (104.16.17.35): icmp_seq=6 ttl=61 time=0.879 ms
64 bytes from 104.16.17.35 (104.16.17.35): icmp_seq=7 ttl=61 time=1.36 ms
64 bytes from 104.16.17.35 (104.16.17.35): icmp_seq=8 ttl=61 time=1.35 ms

Any suggestions? Thank you

**Comment by xiya233** [comment]
[root@xxx duck]# curl -I https://registry.npmjs.org/node-pre-gyp
HTTP/1.1 200 OK
Date: Tue, 23 Oct 2018 13:45:40 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 240533
Connection: keep-alive
Set-Cookie: __cfduid=dbb6b5e870850c1de10250c0a941c06fb1540302340; expires=Wed, 23-Oct-19 13:45:40 GMT; path=/; domain=.registry.npmjs.org; HttpOnly
CF-Cache-Status: HIT
Cache-Control: max-age=300
Accept-Ranges: bytes
CF-RAY: 46e4a53e2c2294f9-NRT
ETag: "a904846b4fd3464f65b0e683baa17cc7"
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Last-Modified: Sun, 12 Aug 2018 03:38:51 GMT
Vary: accept-encoding, accept
Server: cloudflare

**Comment by xiya233** [comment]
After switching to another server, I got a new error:

	> fibers@2.0.0 install /built_app/programs/server/node_modules/fibers
	> node build.js || nodejs build.js
	
	`linux-x64-57` exists; testing
	Binary is fine; exiting
	
	> meteor-dev-bundle@ install /built_app/programs/server
	> node npm-rebuild.js
	
	
	> bufferutil@4.0.0 install /built_app/programs/server/npm/node_modules/bufferutil
	> node-gyp-build
	
	make: Entering directory '/built_app/programs/server/npm/node_modules/bufferutil/build'
	  CC(target) Release/obj.target/bufferutil/src/bufferutil.o
	../src/bufferutil.c: In function 'Init':
	../src/bufferutil.c:155:12: error: too many arguments to function 'napi_create_function'
	   status = napi_create_function(env, NULL, 0, Mask, NULL, &mask);
	            ^
	In file included from ../src/bufferutil.c:2:0:
	/root/.node-gyp/8.4.0/include/node/node_api.h:157:25: note: declared here
	 NAPI_EXTERN napi_status napi_create_function(napi_env env,
	                         ^
	../src/bufferutil.c:158:12: error: too many arguments to function 'napi_create_function'
	   status = napi_create_function(env, NULL, 0, Unmask, NULL, &unmask);
	            ^
	In file included from ../src/bufferutil.c:2:0:
	/root/.node-gyp/8.4.0/include/node/node_api.h:157:25: note: declared here
	 NAPI_EXTERN napi_status napi_create_function(napi_env env,
	                         ^
	../src/bufferutil.c: At top level:
	../src/bufferutil.c:170:1: warning: initialization from incompatible pointer type
	 NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
	 ^
	../src/bufferutil.c:170:1: warning: (near initialization for '_module.nm_register_func')
	bufferutil.target.mk:95: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
	make: Leaving directory '/built_app/programs/server/npm/node_modules/bufferutil/build'
	make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
	gyp ERR! stack     at emitTwo (events.js:125:13)
	gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
	gyp ERR! System Linux 3.10.0-862.11.6.el7.x86_64
	gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /built_app/programs/server/npm/node_modules/bufferutil
	gyp ERR! node -v v8.4.0
	gyp ERR! node-gyp -v v3.6.2
	gyp ERR! not ok 
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! bufferutil@4.0.0 install: `node-gyp-build`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the bufferutil@4.0.0 install script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2018-10-24T05_07_44_055Z-debug.log
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the meteor-dev-bundle@ install script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2018-10-24T05_07_44_099Z-debug.log

**Comment by xiya233** [comment]
After my research, I found this to be a Node.js version compatibility issue.

You should specify Node.js version 8.11.2 in mup.js.

The default 8.4.0 is no longer compatible with "bufferutil", so it will cause the build to fail.

**Comment by guidouil** [comment]
For me the issue was linked with webtorrent version using nAPI so to keep it running I downgraded webtorrent to 99 something. I'm gonna digg this new path 👍

**Comment by guidouil** [comment]
Took me a while ^^
Now the deploy works again :)
Thanks @xiya233
